### ISSUE TITLE
The tracking issue for adding rich API

### ISSUE THREAD

**Issue by w41ter** [w41ter/sekas#1]
- [x] #2
- [ ] #9
- [x] #4
- [x] #7
- [ ] Check confliction during `WriteConditionBuilder`
- [ ] Support watch range and key
- [ ] CAS should return the unexpected value
- [ ] Add a way to simplify test construction
- [ ] Refactor `DatabaseDesc`, `CollectionDesc`, `ShardDesc`
- [ ] Error contains stack info
- [x] #16
- [ ] BatchWrite support Atomic OP
- [x] #24
- [x] #19
- [ ] #28
- [x] #26
- [ ] Add scope-based log macros
- [ ] Add in-mem store for local meta
