### ISSUE TITLE
The roadmap of the next sekas version

### ISSUE THREAD

**Issue by w41ter** [w41ter/sekas#41]
This version aims to provide a basic fault-tolerant, scalable transactional key-value store.

Before releasing the new version, we need to solve below issues:

Features:

- [ ] Add a `write_batch` API to provide cross-shard atomic writes
- [ ] Support CAS operation
- [ ] Support multi-version snapshot
- [ ] Support online shard moving
- [ ] Define the API of the Rust SDK
- [ ] Add a proxy to service the Rust SDK
- [ ] Support watch API

Improvement:

- [ ] Add task group to manage async task lifecycle
- [ ] Stop all serving replicas when dropping node, then pass test `node::tests::create_then_bootstrap_replica`.
- [ ] Migrate the code of `raft_engine` to a sub-crate for easier maintenance.
- [ ] Migrate the code of `raft-rs` to a sub-crate for easier maintenance.
- [ ] Rename shard migration to shard move and refactor it
- [ ] Change the Master location query API from push to pull.

Testing:

- [ ] Add unit for `eval_scan.rs`
- [ ] Simplify the testing framework and ensure the stability of integration testing

Some things we plan to do in future releases:
- Backup/restore
- Data ingestion
- A storage engine
- A RPC framework, compatible with bRPC, gRPC
- A runtime to schedule tasks in a separate task group.
